---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services

- Total:
    - Xlog:
        icon: https://raw.githubusercontent.com/Crossbell-Box/xLog/main/public/assets/logo.svg
        href: https://fatdoge.cn
        description: fatdoge.cn
    - Hexo:
        icon: hexo
        href: https://fatdoge.im
        description: fatdoge.im
    - Github:
        icon: github
        href: https://github.com/fatdoge
        description: '@fatdoge'
    - GPTGenius:
        icon: github
        href: https://github.com/GPTGenius/chatgpt-vercel
        description: chatgpt-vercel
